"""add indexes

Revision ID: fc79cc8430d9
Revises: f6149be83f64
Create Date: 2024-10-31 13:26:18.724308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc79cc8430d9'
down_revision = 'f6149be83f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authors_birth_date'), ['birth_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_authors_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_authors_name'), ['name'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_publish_date'), ['publish_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_title'))
        batch_op.drop_index(batch_op.f('ix_books_publish_date'))
        batch_op.drop_index(batch_op.f('ix_books_description'))
        batch_op.drop_index(batch_op.f('ix_books_author_id'))

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_name'))
        batch_op.drop_index(batch_op.f('ix_authors_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_authors_birth_date'))

    # ### end Alembic commands ###
